"""Init

Revision ID: 959d078b8a86
Revises: 
Create Date: 2023-09-30 23:06:00.068718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959d078b8a86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('GroupID', sa.Integer(), nullable=False),
    sa.Column('GroupName', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('GroupID')
    )
    op.create_table('teachers',
    sa.Column('TeacherID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=250), nullable=False),
    sa.Column('LastName', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('TeacherID')
    )
    op.create_table('lessons',
    sa.Column('LessonID', sa.Integer(), nullable=False),
    sa.Column('LessonName', sa.String(length=250), nullable=False),
    sa.Column('TeacherID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TeacherID'], ['teachers.TeacherID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LessonID')
    )
    op.create_table('students',
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=250), nullable=False),
    sa.Column('LastName', sa.String(length=250), nullable=False),
    sa.Column('GroupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GroupID'], ['groups.GroupID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('rating',
    sa.Column('RateID', sa.Integer(), nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('LessonID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['LessonID'], ['lessons.LessonID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StudentID'], ['students.StudentID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RateID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('students')
    op.drop_table('lessons')
    op.drop_table('teachers')
    op.drop_table('groups')
    # ### end Alembic commands ###
