[tool.poetry]
name = "hm"
version = "0.1.0"
description = ""
authors = ["Crack"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
alembic = "^1.12.0"
sqlalchemy = "^2.0.21"
faker = "^19.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
